
title:Welcome to My Portfolio Hello! My name is Giovanni

description: i play sports like soccer and i like to travel 

baseurl: "" # leave empty since this is your user page

url: "https://elvgio.github.io" # replace YOURUSERNAME with your GitHub username

theme: jekyll-theme-midnight # replace “merlot” with your chosen theme from the list

